### ISSUE TITLE
Can't connect to X11 window server using ':0'

### ISSUE THREAD

**Issue by jehy** [gtrafimenkov/docker-codeswarm#2]
Could you please help? I think that's a newbie error and I really want to try code swarm : )

> Parsing SVN log...
> Parsed 57504 commits
> Generating XML from 133589 events...
> No protocol specified
> Exception in thread "main" java.lang.InternalError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.
>         at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
>         at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
>         at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:110)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
>         at java.lang.Class.forName0(Native Method)
>         at java.lang.Class.forName(Class.java:195)
>         at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:102)
>         at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:81)
>         at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:120)
>         at java.lang.Class.forName0(Native Method)
>         at java.lang.Class.forName(Class.java:195)
>         at java.awt.Toolkit$2.run(Toolkit.java:869)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:861)
>         at processing.core.PApplet.<clinit>(PApplet.java:202)

Ubuntu 17.10, KDE 5

**Comment by gtrafimenkov** [comment]
Try running command `xhost +"local:docker@"` before starting the container.  It helped me starting the container on Ubuntu 18.04.

The answer is from https://github.com/jessfraz/dockerfiles/issues/329

**Comment by tsylla** [comment]
Thank you very much. It help me too

**Comment by ibadami** [comment]
@gtrafimenkov  saved my day! Thank you.

**Comment by raven2cz** [comment]
it works on arch too. Necessary to install first [xorg-xhost](https://archlinux.org/packages/extra/x86_64/xorg-xhost/).
Thanks for help!
